### ISSUE TITLE
Get-WTCurrentRelease $wtsettings.refresh() error: "You cannot call a method on a null-valued expression."

### ISSUE THREAD

**Issue by glenncarr** [jdhitsolutions/WTToolbox#13]
Receiving the following error:

![image](https://user-images.githubusercontent.com/367292/102653980-66e09b00-4135-11eb-99a2-0d624d4ea4e4.png)

**Comment by jdhitsolutions** [comment]
I wonder if this is because you are using an out-of-the-box profile. What does your settings.json file look like for this profile?

**Comment by jdhitsolutions** [comment]
If you run `get-variable wt*` you should see 4 values.

WTDefaults
WTDefaultsPath
WTSettings
WTSettingsPath

Do you?

**Comment by jdhitsolutions** [comment]
You might also run `import-module wttoolbox -force -verbose` and look for any Verbose messages that show 'Failed'

**Comment by glenncarr** [comment]
1. Here's my settings.json file, which isn't far from the default:
  [settings.zip](https://github.com/jdhitsolutions/WTToolbox/files/5718499/settings.zip)

1. There are no WT* variables defined according to `get-variable wt*` 

1. There is a failure accessing settings.json with `Import-Module -Name WTToolBox -Force -Verbose`:
```
VERBOSE: Testing for settings.json
VERBOSE: Using path C:\Users\gcarr\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
VERBOSE: Failed to find C:\Users\gcarr\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
```
Complete output:
[WTToolbox-Verbose-Import-Module.txt](https://github.com/jdhitsolutions/WTToolbox/files/5718505/WTToolbox-Verbose-Import-Module.txt)

**Comment by jdhitsolutions** [comment]
This is helpful. Somne followup questions:

1. Does `C:\Users\gcarr\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json` actually exist and have JSON content? 
2. How did you install WindowsTerminal? From the MS Store? Winget? This module?
3. Did you install the stable or release version of Windows Terminal?

**Comment by jdhitsolutions** [comment]
Confirmed the problem when running the preview version. Working on it.

**Comment by glenncarr** [comment]
Yes, it's the preview.  As you know now, the settings.json doesn't exist.  Installed from MS Store.

Thanks,
Glenn

**Comment by jdhitsolutions** [comment]
I just pushed v1.12.0 to the PowerShell Gallery. Update the module and try again.

**Comment by glenncarr** [comment]
Works great - thanks!
![image](https://user-images.githubusercontent.com/367292/102796233-954bb980-4373-11eb-9715-8acc92d512d4.png)

**Comment by jdhitsolutions** [comment]
This is a good reminder that I need to include the Preview build in my testing.
