### ISSUE TITLE
Windows Terminal fails with  "Deployment failed with HRESULT: 0x80073CF0"

### ISSUE THREAD

**Issue by animatco** [jdhitsolutions/WTToolbox#16]
Good Day Jeff,

  when trying to use the Install-WTRelease I am getting the following error. I do not believe it is the Function, but was wondering if you have a suggested fix? It does download the MSIXBundle to the $env:temp directory.

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.
error 0x8007007B: Opening the package from location Microsoft.WindowsTerminal_1.11.3471.0_8wekyb3d8bbwe.msixbundle
failed.
NOTE: For additional information, look for [ActivityId] 7e3e4db8-c04e-0005-c744-967e4ec0d701 in the Event Log or use
the command line Get-AppxLog -ActivityID 7e3e4db8-c04e-0005-c744-967e4ec0d701
At line:39 char:17
+                 Add-AppxPackage -Path $target -ErrorAction stop
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (C:\Users\ANSIBL...bbwe.msixbundle:String) [Add-AppxPackage], FileNotFoundExc
   eption
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by jdhitsolutions** [comment]
This is still a tricky thing to pull off. What version of Windows and what version of PowerShell are you using?

**Comment by animatco** [comment]
Windows Server 2016 std. Powershell 5.1

**Comment by jdhitsolutions** [comment]
Hmm...I wonder if the server platform is missing some necessary parts. I'll have to test. And yes, I am hoping to return to Austin this year.

**Comment by jdhitsolutions** [comment]
I was able to duplicate the error. Now to figure out why.

**Comment by jdhitsolutions** [comment]
Windows Terminal is not supported on Windows Server 2016. This will never work. I'll need to update my documentation.

**Comment by animatco** [comment]
Thank you Jeff for confirming. Hope to see later in the year!
