### ISSUE TITLE
comments and list

### ISSUE THREAD

**Issue by jszabo98** [jdhitsolutions/WTToolbox#2]
I don't necessarily put a space after // for comments in my settings.json file.  convertfrom-json is more forgiving in powershell 7 than powershell 5 for this.  But I've added spaces to work with this module.

This is more on me, but I had copied the defaults.json to settings.json, and it doesn't have a 'list' property, so get-wtcurrent wasn't finding the current profile.  I've started over with the settings.json that comes with it.

Btw I like having the settings folder for easy cd:

$WTSettingsFolder = split-path $WTSettingsPath

**Comment by jdhitsolutions** [comment]
comments are standard in json so they are a bit picky to parse which is why I added the space. I might revisit this to see if there is a better way.

**Comment by jdhitsolutions** [comment]
I'm working on a fix to better handle the settings file. You'll see it in v1.6.0

**Comment by jdhitsolutions** [comment]
v1.6.0 has been released to the PowerShell Gallery which should address these issues.

**Comment by jdavidboyd** [comment]
Huh, I just updated to v1.6.0, and Powershell 7.0.2 still works as before, but **now** in Powershell 5 I get:

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\dboyd\Documents\WindowsPowerShell\Modules\WTToolBox\1.6.0\functions\private.ps1:43 char:118
+ ... -notmatch $pattern -OR $_ -match "ms-appx:\/{3}"}) | ConvertFrom-Json
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand


I don't see anywhere in my settings.json file where I have '//' without a space afterwards, unless it is in some of the URLs for icons....

**Comment by jdhitsolutions** [comment]
JSON in Windows PowerShell is wacky. Can you post your settings file so I can test with it?

**Comment by jdavidboyd** [comment]
Here's my settings.json file.

[settings.dboyd.zip](https://github.com/jdhitsolutions/WTToolbox/files/4912650/settings.dboyd.zip)

**Comment by jdhitsolutions** [comment]
The json cmdlet in Windows PowerShell is very picky. There's nothing "wrong" with your settings file. The same command works just fine in PS 7.

**Comment by jdhitsolutions** [comment]
This will work in Windows PowerShell:

```powershell
 get-content .\settings.json | where {$_ -notmatch "//"} | convertfrom-json
```

**Comment by jdavidboyd** [comment]
That didn't quite seem to do it, but when I changed the existing line to be this

$obj = (Get-Content -path $Global:WTSettingsPath).where({$_ -notmatch "^[\t ]*//"}) | ConvertFrom-Json

it all seems to work ok.

Thanks for the help!
