### ISSUE TITLE
Module is not detecting that Windows Terminal is installed when run from Windows Terminal Preview

### ISSUE THREAD

**Issue by rkeithhill** [jdhitsolutions/WTToolbox#6]
I have both Windows Terminal and Windows Termina Preview installed.  When I have **only** preview running, I get a warning about it not being installed:

![image](https://user-images.githubusercontent.com/5177512/89107316-6b5a2080-d3ed-11ea-8f37-557c3d67c344.png)

However, I don't get this warning from Windows Terminal nor do I get it in preview **IFF** a Windows Terminal session is also open.  And it seems that once this warning goes away, I can't get it to come back.

**Comment by jdhitsolutions** [comment]
During my last update Windows Terminal hadn't started releasing preview builds so my module wasn't taking that into account. I am updating to correct that. Thanks for bringing this up.

**Comment by jdhitsolutions** [comment]
Update to v1.8.0 and see if that works better.

**Comment by rkeithhill** [comment]
I don't see the warning. Thanks.

**Comment by jdhitsolutions** [comment]
I modified the commands to detect if you are running in the preview or stable build. Assuming they don't change things again in the preview.
